engines:
  rubocop:
    enabled: true
    checks:
      Bundler/OrderedGems:
        enabled: false
      Rubocop/Bundler/OrderedGems:
        enabled: false
  scss-lint:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
ratings:
  paths:
  - "**.scss"
  - "**.rb"
  - "client/**.js"
  - "client/**.jsx"
