engines:
  rubocop:
    enabled: true
    checks:
      Bundler/OrderedGems:
        enabled: false
      Rubocop/Bundler/OrderedGems:
        enabled: false
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.rb"
