engines:
  rubocop:
    enabled: true
    checks:
      Bundler/OrderedGems:
        enabled: false
      Rubocop/Bundler/OrderedGems:
        enabled: false
  scss-lint:
    enabled: true
  eslint:
    enabled: true
    paths:
      - "./client/**.jsx"
      - "./client/**.js"
ratings:
  paths:
  - "**.scss"
  - "**.rb"
  - "**.js"
  - "**.jsx"
